trigger:
- manual

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: Bash@3
  displayName: Veracode Static Pipeline Scanner
  
  inputs:
    targetType: inline
    script: |
      pwd
      export VERACODE_API_KEY_ID=$(VERACODE_API_KEY_ID)
      export VERACODE_API_KEY_SECRET=$(VERACODE_API_KEY_SECRET)
      curl -fsS https://tools.veracode.com/veracode-cli/install | sh
      ./veracode configure
      ./veracode scan --source https://github.com/veracode/verademo --type repo --format json --output ./veracode_container_scan.json
      ./veracode sbom --source https://github.com/veracode/verademo --type repo --format json --output ./sbom.json
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'veracode_container_scan.json'
    pathToPublish: '$(System.DefaultWorkingDirectory)/veracode_container_scan.json'
  displayName: 'Publish veracode_container_scan.json Artifact'
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'sbom.json'
    pathToPublish: '$(System.DefaultWorkingDirectory)/sbom.json'
  displayName: 'Publish Veracode sbom.json Artifact'