apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  hostIPC: true  
  securityContext:
    seLinuxOptions:
      type: custom
  containers:
    - command: ["sh", "-c", "echo 'Hello' && sleep 1h"]
      image: busybox:latest
      name: hello
  volumes:
    - name: test-volume
      hostPath:
        path: "/var/run/docker.sock"
        type: Directory
